In [1]:
type(2)

int

In [2]:
type(2.1)

float

In [1]:
 type(4.2)

float

In [1]:
show env

SyntaxError: invalid syntax (<ipython-input-1-edf9433b99a1>, line 1)

In [2]:
conda info


     active environment : base
    active env location : C:\ProgramData\Anaconda3
       user config file : C:\Users\Lee\.condarc
 populated config files : C:\Users\Lee\.condarc
          conda version : 4.9.2
    conda-build version : 3.18.11
         python version : 3.7.7.final.0
Note: you may need to restart the kernel to use updated packages.
       virtual packages : __cuda=11.1=0

                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\p

In [4]:
from __future__ import print_function

In [5]:
import torch

In [6]:
x = torch.empty(5,3)

In [7]:
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
x = torch.rand(5,3)

In [9]:
print(x)

tensor([[2.4612e-02, 6.3119e-01, 3.5421e-02],
        [2.4935e-01, 5.5712e-01, 7.3735e-02],
        [3.6714e-01, 3.7647e-01, 2.4674e-01],
        [4.0114e-01, 6.3087e-01, 2.2850e-01],
        [9.9013e-01, 6.8748e-04, 8.5868e-01]])


In [8]:
import numpy as np


In [9]:
a = np.array([0,1,2,3])

In [10]:
b = np.array([4,5,6,7])

In [11]:
c = np.array([[0,1,2,3],[4,5,6,7]])

In [12]:
d = np.zeros((2,5))

In [13]:
e = np.random.rand(2,5)

In [14]:
print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0.07839933 0.54700469 0.13225595 0.93807321 0.80896967]
 [0.56814809 0.27908742 0.980385   0.24911224 0.80826857]]


In [8]:
print(a * b)

[ 0  5 12 21]


In [9]:
print(a * c)

[[ 0  1  4  9]
 [ 0  5 12 21]]


In [10]:
print(a * d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
print(a * e)

ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [12]:
a = np.zeros((1,4))

In [13]:
b = np.zeros((4,3))

In [14]:
c = a.dot(b)

In [15]:
print(c.shape)

(1, 3)


In [16]:
d = a.dot(b)

In [17]:
knob = 0.5

In [18]:
input = 0.5
pred_act = 0.8
pred = input * knob

In [19]:
error = (pred - pred_act) ** 2
print(error)

0.30250000000000005


In [53]:
weight = 0.5
input = 0.5
goal_prediction = 0.8

step_amount = 0.001

for n in range(20):
    prediction = input * weight
    error = (prediction - goal_prediction) ** 2
    weight_delta = (prediction - goal_prediction) * input
    alpha = 0.01
    weight -= weight_delta
    #weight -= weight_delta * alpha
    
    print("iteration:" + str(n) + " Error:" + str(error) + " Prediction:" + str(prediction) + " weight:" + str(weight))
    
#     up_prediction = input * (weight + step_amount)
#     up_error = (goal_prediction - up_prediction) ** 2
    
#     down_prediction = input * (weight - step_amount)
#     down_error = (goal_prediction - down_prediction) ** 2
    
#     if(down_error < up_error):
#         weight = weight - step_amount
        
#     if(down_error >= up_error):
#         weight = weight + step_amount

iteration:0 Error:0.30250000000000005 Prediction:0.25 weight:0.775
iteration:1 Error:0.17015625000000004 Prediction:0.3875 weight:0.9812500000000001
iteration:2 Error:0.095712890625 Prediction:0.49062500000000003 weight:1.1359375
iteration:3 Error:0.05383850097656251 Prediction:0.56796875 weight:1.251953125
iteration:4 Error:0.03028415679931642 Prediction:0.6259765625 weight:1.33896484375
iteration:5 Error:0.0170348381996155 Prediction:0.669482421875 weight:1.4042236328125
iteration:6 Error:0.00958209648728372 Prediction:0.70211181640625 weight:1.453167724609375
iteration:7 Error:0.005389929274097089 Prediction:0.7265838623046875 weight:1.4898757934570312
iteration:8 Error:0.0030318352166796153 Prediction:0.7449378967285156 weight:1.5174068450927733
iteration:9 Error:0.0017054073093822882 Prediction:0.7587034225463867 weight:1.53805513381958
iteration:10 Error:0.0009592916115275371 Prediction:0.76902756690979 weight:1.553541350364685
iteration:11 Error:0.0005396015314842384 Prediction:

In [3]:
weight, goal_pred, input = (0.0, 0.8, 1.1)
for iteration in range(4):
    print("-----\nWeight:" + str(weight))
    pred = input * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = delta * input
    weight = weight - weight_delta
    print("Error:" + str(error) + " Prediction:" + str(pred))
    print("Delta:" + str(delta) + " Weight Delta:" + str(weight_delta))

-----
Weight:0.0
Error:0.6400000000000001 Prediction:0.0
Delta:-0.8 Weight Delta:-0.8800000000000001
-----
Weight:0.8800000000000001
Error:0.02822400000000005 Prediction:0.9680000000000002
Delta:0.16800000000000015 Weight Delta:0.1848000000000002
-----
Weight:0.6951999999999999
Error:0.0012446784000000064 Prediction:0.76472
Delta:-0.03528000000000009 Weight Delta:-0.0388080000000001
-----
Weight:0.734008
Error:5.4890317439999896e-05 Prediction:0.8074088
Delta:0.007408799999999993 Weight Delta:0.008149679999999992


In [128]:
weight = 0.5
goal_pred = 0.8
input = 3
for n in range(20):
    pred = input * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = input * delta
    alpha = 0.01
    print("iteration: ", n+1, "\n input: ", input, "\n weight: ", weight)
    print(" Prediction = ", input, " * ", weight, " = ", pred)
    print(" delta: ", delta, "\n error: ", error, "\n weight_delta: ", weight_delta)
    weight -= weight_delta * alpha
    print(" new weight: ", weight)
    

iteration:  1 
 input:  3 
 weight:  0.5
 Prediction =  3  *  0.5  =  1.5
 delta:  0.7 
 error:  0.48999999999999994 
 weight_delta:  2.0999999999999996
 new weight:  0.479
iteration:  2 
 input:  3 
 weight:  0.479
 Prediction =  3  *  0.479  =  1.4369999999999998
 delta:  0.6369999999999998 
 error:  0.4057689999999997 
 weight_delta:  1.9109999999999994
 new weight:  0.45988999999999997
iteration:  3 
 input:  3 
 weight:  0.45988999999999997
 Prediction =  3  *  0.45988999999999997  =  1.37967
 delta:  0.5796699999999999 
 error:  0.33601730889999987 
 weight_delta:  1.7390099999999997
 new weight:  0.44249989999999995
iteration:  4 
 input:  3 
 weight:  0.44249989999999995
 Prediction =  3  *  0.44249989999999995  =  1.3274996999999997
 delta:  0.5274996999999997 
 error:  0.27825593350008965 
 weight_delta:  1.582499099999999
 new weight:  0.42667490899999994
iteration:  5 
 input:  3 
 weight:  0.42667490899999994
 Prediction =  3  *  0.42667490899999994  =  1.2800247269999998


In [4]:
# multiple input to 1 output
toes = [8.5 , 9.5, 9.9, 9.0]
winloss = [0.65, 0.8, 0.8, 0.9]
fans = [1.2 , 1.3, 0.5, 1.0]

# multiple inputs with only 1 output
input = [toes[0], winloss[0], fans[0]]
weights = [0.1, 0.2, -.1]
alpha = 0.01

win_or_lose_binary = [1, 1, 0, 1]
# prediction tries to get close to true value
true = win_or_lose_binary[0]

def neural_network(inp, wei):
    pred = 0
    for i in range(len(inp)):
        pred += (inp[i] * wei[i])
    return pred

def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

for iter in range(3):
    # multiply weights * input
    prediction = neural_network(input, weights)
    # calc error
    error = (prediction - true) ** 2
    # calc raw error
    delta = prediction - true
    # calc weight delta to correct for scaling, negative reversal, and stopping
    # basically raw error * input
    weight_deltas = ele_mul(delta, input)
    
    # print out variables
    print("input: ", input)
    print("weights: ", weights)
    print("prediction: ", prediction)
    print("true value: ", true)
    print("error: ", error)
    print("delta raw error", delta)
    print("weight deltas: " , weight_deltas)

    # update new weights
    for i in range(len(weights)):
        weights[i] -= alpha * weight_deltas[i]
    print("new weights:", weights)
    print("\n")




input:  [8.5, 0.65, 1.2]
weights:  [0.1, 0.2, -0.1]
prediction:  0.8600000000000001
true value:  1
error:  0.01959999999999997
delta raw error -0.1399999999999999
weight deltas:  [-1.189999999999999, -0.09099999999999994, -0.16799999999999987]
new weights: [0.1119, 0.20091, -0.09832]


input:  [8.5, 0.65, 1.2]
weights:  [0.1119, 0.20091, -0.09832]
prediction:  0.9637574999999999
true value:  1
error:  0.0013135188062500048
delta raw error -0.036242500000000066
weight deltas:  [-0.30806125000000056, -0.023557625000000044, -0.04349100000000008]
new weights: [0.11498061250000001, 0.20114557625, -0.09788509000000001]


input:  [8.5, 0.65, 1.2]
weights:  [0.11498061250000001, 0.20114557625, -0.09788509000000001]
prediction:  0.9906177228125002
true value:  1
error:  8.802712522307997e-05
delta raw error -0.009382277187499843
weight deltas:  [-0.07974935609374867, -0.006098480171874899, -0.011258732624999811]
new weights: [0.1157781060609375, 0.20120656105171877, -0.09777250267375001]




In [153]:
print(prediction)

0.9906177228125002


In [154]:
print(pred)

0.9166499331155198


In [5]:
# freeze weight 1, and nn will still 'learn' without it where weight 1 may hold predictive power.
# the model effective learns to predict without it, and thus never incorporates it into its prediction
toes = [8.5 , 9.5, 9.9, 9.0]
winloss = [0.65, 0.8, 0.8, 0.9]
fans = [1.2 , 1.3, 0.5, 1.0]

# multiple inputs with only 1 output
input = [toes[0], winloss[0], fans[0]]
weights = [0.1, 0.2, -.1]
# adjust alpha
alpha = 0.3

win_or_lose_binary = [1, 1, 0, 1]
# prediction tries to get close to true value
true = win_or_lose_binary[0]

def neural_network(inp, wei):
    pred = 0
    for i in range(len(inp)):
        pred += (inp[i] * wei[i])
    return pred

def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

for iter in range(5):
    # multiply weights * input
    prediction = neural_network(input, weights)
    # calc error
    error = (prediction - true) ** 2
    # calc raw error
    delta = prediction - true
    # calc weight delta to correct for scaling, negative reversal, and stopping
    weight_deltas = ele_mul(delta, input)
    # freeze weight
    weight_deltas[0] = 0
    # print out variables
    print("input: ", input)
    print("weights: ", weights)
    print("prediction: ", prediction)
    print("error: ", error)
    print("delta raw error", delta)
    print("weight deltas: " , weight_deltas)

    # update new weights
    for i in range(len(weights)):
        weights[i] -= alpha * weight_deltas[i]
    print("new weights:", weights)
    print("\n")

input:  [8.5, 0.65, 1.2]
weights:  [0.1, 0.2, -0.1]
prediction:  0.8600000000000001
error:  0.01959999999999997
delta raw error -0.1399999999999999
weight deltas:  [0, -0.09099999999999994, -0.16799999999999987]
new weights: [0.1, 0.2273, -0.04960000000000005]


input:  [8.5, 0.65, 1.2]
weights:  [0.1, 0.2273, -0.04960000000000005]
prediction:  0.9382250000000001
error:  0.003816150624999989
delta raw error -0.06177499999999991
weight deltas:  [0, -0.040153749999999946, -0.07412999999999989]
new weights: [0.1, 0.239346125, -0.02736100000000008]


input:  [8.5, 0.65, 1.2]
weights:  [0.1, 0.239346125, -0.02736100000000008]
prediction:  0.97274178125
error:  0.000743010489422852
delta raw error -0.027258218750000007
weight deltas:  [0, -0.017717842187500006, -0.032709862500000006]
new weights: [0.1, 0.24466147765625, -0.017548041250000077]


input:  [8.5, 0.65, 1.2]
weights:  [0.1, 0.24466147765625, -0.017548041250000077]
prediction:  0.9879723109765626
error:  0.00014466530324451716
delt

In [40]:
# MULTIPLE OUTPUTS FOR 1 INPUT
# input
winloss = [0.65, 1.0, 1.0, 0.9]
input = winloss[0]
weights = [0.3, 0.2, 0.9]
alpha = 0.1

# output
hurt = [0.1, 0.0, 0.0, 0.1]
win = [ 1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]
# prediction tries to get close to true value
true = [hurt[0], win[0], sad[0]]

def neural_network(inp, wei):
    pred = 0
    for i in range(len(inp)):
        pred += (inp[i] * wei[i])
    return pred

def neural_network_multiout(inp, wei):
    pred = [0,0,0]
    for i in range(len(wei)):
        pred[i] = (inp * wei[i])
    return pred

def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

for iter in range(3):
    # multiply weights * input
    prediction = neural_network_multiout(input, weights)

    # calc error, adjust based on data
    error = [0,0,0]
    delta = [0,0,0]
    
    for i in range(len(true)):
        error[i] = (prediction[i] - true[i]) ** 2
        delta[i] = (prediction[i] - true[i])
        
    # calc weight delta to correct for scaling, negative reversal, and stopping
    weight_deltas = ele_mul(input, delta)

    # print out variables
    print("input: ", input)
    print("weights: ", weights)
    print("prediction: ", prediction)
    print("error: ", error)
    print("delta raw error", delta)
    print("weight deltas: " , weight_deltas)

    # update new weights
    for i in range(len(weights)):
        weights[i] -= alpha * weight_deltas[i]
    print("new weights:", weights)
    print("\n")

input:  0.65
weights:  [0.3, 0.2, 0.9]
prediction:  [0.195, 0.13, 0.5850000000000001]
error:  [0.009025, 0.7569, 0.2352250000000001]
delta raw error [0.095, -0.87, 0.4850000000000001]
weight deltas:  [0.061750000000000006, -0.5655, 0.3152500000000001]
new weights: [0.293825, 0.25655, 0.868475]


input:  0.65
weights:  [0.293825, 0.25655, 0.868475]
prediction:  [0.19098625, 0.1667575, 0.56450875]
error:  [0.008278497689062499, 0.69429306380625, 0.21576837882656252]
delta raw error [0.09098624999999999, -0.8332425, 0.46450875]
weight deltas:  [0.059141062499999994, -0.541607625, 0.3019306875]
new weights: [0.28791089375, 0.3107107625, 0.83828193125]


input:  0.65
weights:  [0.28791089375, 0.3107107625, 0.83828193125]
prediction:  [0.1871420809375, 0.20196199562500003, 0.5448832553125]
error:  [0.007593742270117802, 0.6368646564268324, 0.19792111085744712]
delta raw error [0.0871420809375, -0.7980380043749999, 0.44488325531250006]
weight deltas:  [0.056642352609375, -0.5187247028437499, 

In [6]:
# MULTIPLE INPUTS & OUTPUTS
import numpy as np
# input
toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
#          toes, win, fans
weights = [[0.1, 0.1, -0.3],# hurt
           [0.1, 0.2, 0.0], # win
           [0.0, 1.3, 0.1]] # sad

alpha = 0.01

# output
hurt = [0.1, 0.0, 0.0, 0.1]
win = [ 1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]

# prediction tries to get close to true value
true = [hurt[0], win[0], sad[0]]

def neural_network(inp, wei):
    pred = 0
    for i in range(len(inp)):
        pred += (inp[i] * wei[i])
    return pred

def neural_network_multiout(inp, wei):
    pred = [0,0,0]
    for i in range(len(wei)):
        pred[i] = (inp * wei[i])
    return pred

def vect_mat_mult(vect_input, matrix_weights):
    assert(len(vect_input) == len(matrix_weights))
    output = [0,0,0]
    for i in range(len(vect_input)):
        output[i] = w_sum(vect_input, matrix_weights[i])
    return output

def w_sum(input2, weight):
    p = 0
    #print("input: ", input2)
    #print("weight: ", weight)
    for i in range(len(input2)):
        p += input2[i] * weight[i]
    return p

def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

def ele_mul_2(vector_a, vector_b):
    outp = np.zeros((len(vector_a), len(vector_b)))
    print(outp)
                    
    for i in range(len(vector_a)):
        for j in range(len(vector_b)):
            outp[i][j] = vector_a[i] * vector_b[j]
    return outp

for iter in range(2):
    # multiply weights * input
    prediction = vect_mat_mult(input, weights)

    # calc error, adjust based on data
    error = [0,0,0]
    delta = [0,0,0]
    
    for i in range(len(true)):
        error[i] = (prediction[i] - true[i]) ** 2
        delta[i] = (prediction[i] - true[i])
        
    print("input: ", input)
    print("weights: ", weights)
    print("prediction: ", prediction)
    print("error: ", error)
    print("delta raw error", delta)   
    # calc weight delta to correct for scaling, negative reversal, and stopping
    weight_deltas = ele_mul_2(input, delta)

    # print out variables
    print("input: ", input)
    print("weights: ", weights)
    print("prediction: ", prediction)
    print("error: ", error)
    print("delta raw error", delta)
    print("weight deltas: " , weight_deltas)

    # update new weights
    for i in range(len(weights)):
        for j in range(len(weights[0])):
            weights[i][j] -= alpha * weight_deltas[i][j]
    print("new weights:", weights)
    print("\n")

input:  [8.5, 0.65, 1.2]
weights:  [[0.1, 0.1, -0.3], [0.1, 0.2, 0.0], [0.0, 1.3, 0.1]]
prediction:  [0.555, 0.9800000000000001, 0.9650000000000001]
error:  [0.20702500000000007, 0.0003999999999999963, 0.7482250000000001]
delta raw error [0.45500000000000007, -0.019999999999999907, 0.8650000000000001]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
input:  [8.5, 0.65, 1.2]
weights:  [[0.1, 0.1, -0.3], [0.1, 0.2, 0.0], [0.0, 1.3, 0.1]]
prediction:  [0.555, 0.9800000000000001, 0.9650000000000001]
error:  [0.20702500000000007, 0.0003999999999999963, 0.7482250000000001]
delta raw error [0.45500000000000007, -0.019999999999999907, 0.8650000000000001]
weight deltas:  [[ 3.8675  -0.17     7.3525 ]
 [ 0.29575 -0.013    0.56225]
 [ 0.546   -0.024    1.038  ]]
new weights: [[0.061325, 0.1017, -0.373525], [0.0970425, 0.20013, -0.005622500000000002], [-0.0054600000000000004, 1.30024, 0.08962]]


input:  [8.5, 0.65, 1.2]
weights:  [[0.061325, 0.1017, -0.373525], [0.0970425, 0.20013, -0.005622500000000002], [-