In [1]:
import numpy as np
weights = np.array([0.5, 0.48, -0.71])
alpha = 0.1

streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ],
                          [ 0, 1, 1 ],
                          [ 1, 0, 1 ] ])

walk_vs_stop = np.array( [ 0, 1, 0, 1, 1, 0 ] )

#input = streetlights[0]
#true = walk_vs_stop[0]

for i in range(40):
    error_all_lights = 0
    #print(input)
    #print(true)
    
    # for every output make prediction and update weights
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        #print("input: ", input)
        true = walk_vs_stop[row_index]
        
        prediction = input.dot(weights)
        error = (prediction - true) ** 2
        error_all_lights += error
        delta = prediction - true
        weights = weights - (alpha * (input * delta))
    
    print("iteration",i , "\nerror: ", error_all_lights, "\nPrediction:", prediction, "\n")
    print("weights: " , weights)

iteration 0 
error:  2.7024054445006405 
Prediction: 0.17083920000000008 

weights:  [ 0.54285508  0.7230902  -0.40618372]
iteration 1 
error:  0.9713871009418902 
Prediction: 0.2650462955328 

weights:  [ 0.50200362  0.84446162 -0.28996659]
iteration 2 
error:  0.5544909496538875 
Prediction: 0.25334321214885613 

weights:  [ 0.44207731  0.91511355 -0.23940274]
iteration 3 
error:  0.36708619229340766 
Prediction: 0.21406568129562475 

weights:  [ 0.38353468  0.96138672 -0.21228214]
iteration 4 
error:  0.2538911867367981 
Prediction: 0.17247461940374073 

weights:  [ 0.33193662  0.99382412 -0.19395693]
iteration 5 
error:  0.17988437064999874 
Prediction: 0.1358504230820905 

weights:  [ 0.28799059  1.01721762 -0.17931025]
iteration 6 
error:  0.13029670737244717 
Prediction: 0.10554898573022198 

weights:  [ 0.25096343  1.03413834 -0.16652425]
iteration 7 
error:  0.09654229043957849 
Prediction: 0.08111043451123354 

weights:  [ 0.21981405  1.04620332 -0.15492571]
iteration 8 
erro

In [3]:
import numpy as np


np.random.seed(1)

def relu(x):
    return (x > 0) * x

def relu2deriv(y):
    return y>0

lights = np.array([[1, 0, 1],
                   [0, 1, 1], 
                   [0, 0, 1], 
                   [1, 1, 1]])

walk_stop = np.array([1, 1, 0, 0])
alpha = 0.2
hidden_size = 3

#print(np.random.randn(3,hidden_size))

weights_0_1 = 2*np.random.rand(3, hidden_size) - 1
weights_1_2 = 2*np.random.rand(hidden_size,1) - 1

# input layer 0 is the first array up to the 1st element of nested not including
layer0 = lights[0:1]

# input to layer 1 is the dot product of the weights and input
layer1 = np.dot(layer0, weights_0_1)
# apply relu fuction
layer1 = relu(layer1)

layer2 = np.dot(layer1, weights_1_2)

print("layer0: ", layer0, "\nlayer1: ", layer1, "\nlayer2: ", layer2)

# prediction - true
error = (layer2 - walk_stop[0]) ** 2
print("error: ", error)
# calc raw error
layer_2_delta = (layer2 - walk_stop[0])
print("raw error", layer_2_delta)

# multiply raw error back through network by the weights
#print("weights", weights_1_2)
#print("weights T", weights_1_2.T)
layer_1_delta = layer_2_delta.dot(weights_1_2.T)
#print(layer_1_delta)
layer_1_delta *= relu2deriv(layer1)
print("raw error relu: ", layer_1_delta)

# multiply input by raw error for each layer
weight_delta_1_2 = layer1.T.dot(layer_2_delta)
weight_delta_0_1 = layer0.T.dot(layer_1_delta)

# update weights
weights_1_2 -= alpha * weight_delta_1_2
weights_0_1 -= alpha * weight_delta_0_1


layer0:  [[1 0 1]] 
layer1:  [[-0.          0.13177044 -0.        ]] 
layer2:  [[-0.02129555]]
error:  [[1.0430446]]
raw error [[-1.02129555]]
raw error relu:  [[-0.          0.16505257 -0.        ]]


In [33]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

def relu2deriv(y):
    return y>0

lights = np.array([[1, 0, 1],
                   [0, 1, 1], 
                   [0, 0, 1], 
                   [1, 1, 1]])

walk_stop = np.array([[1, 1, 0, 0]]).T
alpha = 0.2
hidden_size = 4

#print(np.random.randn(3,hidden_size))

weights_0_1 = 2*np.random.rand(3, hidden_size) - 1
weights_1_2 = 2*np.random.rand(hidden_size,1) - 1


for iteration in range(60):
    layer_2_error = 0
    
    for i in range(len(lights)):
        # input layer 0 is the first array up to the 1st element of nested not including
        layer0 = lights[i:i+1]
        layer1 = relu(np.dot(layer0, weights_0_1))
        layer2 = np.dot(layer1, weights_1_2)

        print("layer0: ", layer0, "\nlayer1: ", layer1, "\nlayer2: ", layer2)

        # prediction - true
        layer_2_error += np.sum((layer2 - walk_stop[i:i+1]) ** 2)
        layer_2_delta = (layer2 - walk_stop[i:i+1])
        #print("raw error", layer_2_delta)

        # multiply raw error back through network by the weights
        #print("weights", weights_1_2)
        #print("weights T", weights_1_2.T)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer1)
        #print("raw error relu: ", layer_1_delta)

        # multiply input by raw error for each layer
        weight_delta_1_2 = layer1.T.dot(layer_2_delta)
        weight_delta_0_1 = layer0.T.dot(layer_1_delta)
        
        print("weights_1_2: ", weights_1_2, "\nweights_0_1:", weights_0_1)
        # update weights
        weights_1_2 -= alpha * weight_delta_1_2
        weights_0_1 -= alpha * weight_delta_0_1

    if(iteration % 10 == 9):
        print("error: ", layer_2_error)

layer0:  [[1 0 1]] 
layer1:  [[-0.          0.51828245 -0.         -0.        ]] 
layer2:  [[0.39194327]]
weights_1_2:  [[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]] 
weights_0_1: [[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
layer0:  [[0 1 1]] 
layer1:  [[-0.         -0.         -0.          0.06156045]] 
layer2:  [[0.02098811]]
weights_1_2:  [[-0.5910955 ]
 [ 0.8192639 ]
 [-0.94522481]
 [ 0.34093502]] 
weights_0_1: [[-0.16595599  0.53261573 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.16960021 -0.16161097  0.370439  ]]
layer0:  [[0 0 1]] 
layer1:  [[-0.          0.16960021 -0.          0.43719489]] 
layer2:  [[0.29327219]]
weights_1_2:  [[-0.5910955 ]
 [ 0.8192639 ]
 [-0.94522481]
 [ 0.3529887 ]] 
weights_0_1: [[-0.16595599  0.53261573 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.24212266]
 [-0.

weights_1_2:  [[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.00347565]] 
weights_0_1: [[-0.16595599  0.91056768 -0.99977125 -0.88006497]
 [-0.70648822 -0.92794391 -0.62747958  0.77036319]
 [-0.20646505 -0.03308324 -0.16161097  0.12217277]]
layer0:  [[0 1 1]] 
layer1:  [[-0.         -0.         -0.          0.89253596]] 
layer2:  [[0.8956381]]
weights_1_2:  [[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.00347565]] 
weights_0_1: [[-0.16595599  0.91056768 -0.99977125 -0.88006497]
 [-0.70648822 -0.92794391 -0.62747958  0.77036319]
 [-0.20646505 -0.03308324 -0.16161097  0.12217277]]
layer0:  [[0 0 1]] 
layer1:  [[-0.        -0.        -0.         0.1431177]] 
layer2:  [[0.14628131]]
weights_1_2:  [[-0.5910955 ]
 [ 1.13962134]
 [-0.94522481]
 [ 1.022105  ]] 
weights_0_1: [[-0.16595599  0.91056768 -0.99977125 -0.88006497]
 [-0.70648822 -0.92794391 -0.62747958  0.79130811]
 [-0.20646505 -0.03308324 -0.16161097  0.1431177 ]]
layer0:  [[1 1 1]] 
layer1:  [[-0.         -0.         -0.      

In [1]:
from platform import python_version

print(python_version())

3.7.7


In [31]:
#train data
import sys, numpy as np
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
# TRAIN IMAGES
train_images = (x_train[0:1000].reshape(1000, 28 * 28) / 255)
train_labels = np.zeros((len(y_train[0:1000]), 10))

for i, l in enumerate(y_train[0:1000]):
    train_labels[i][l] = 1

# TEST IMAGES
test_images = x_test.reshape(len(x_test), 28 * 28) / 255
test_labels = np.zeros((len(y_test), 10))

images = train_images
labels = train_labels

for i, l in enumerate(y_test):
    test_labels[i][l] = 1

np.random.seed(1)
relu = lambda x: (x >= 0) * x
relu2deriv = lambda x: x >= 0
alpha, iterations, hidden_size, pixels_per_image, num_labels = (0.005, 350, 40, 784, 10)

weights_0_1 = 0.2 * np.random.random((pixels_per_image, hidden_size)) - 0.1
weights_1_2 = 0.2 * np.random.random((hidden_size, num_labels)) - 0.1

for j in range(iterations):
    error, correct_cnt = 0.0, 0

    for i in range(len(images)):
        layer_0 = images[i:i + 1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)
        
        error += np.sum((labels[i:i + 1] - layer_2) ** 2)
        correct_cnt += int(np.argmax(layer_2) == \
                           np.argmax(labels[i:i + 1]))
        layer_2_delta = (labels[i:i + 1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) \
                        * relu2deriv(layer_1)
        
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
        
            

    if j % 10 == 0:
        sys.stdout.write("\r"+ \
        " I:"+str(j)+ \
        " Error:" + str(error/float(len(images)))[0:5] +\
        " Correct:" + str(correct_cnt/float(len(images))))
        print()


 I:0 Error:0.722 Correct:0.537
 I:10 Error:0.312 Correct:0.901
 I:20 Error:0.260 Correct:0.93
 I:30 Error:0.232 Correct:0.946
 I:40 Error:0.215 Correct:0.956
 I:50 Error:0.204 Correct:0.966
 I:60 Error:0.194 Correct:0.967
 I:70 Error:0.186 Correct:0.975
 I:80 Error:0.179 Correct:0.979
 I:90 Error:0.172 Correct:0.981
 I:100 Error:0.166 Correct:0.984
 I:110 Error:0.161 Correct:0.984
 I:120 Error:0.157 Correct:0.986
 I:130 Error:0.153 Correct:0.99
 I:140 Error:0.149 Correct:0.991
 I:150 Error:0.145 Correct:0.991
 I:160 Error:0.141 Correct:0.992
 I:170 Error:0.138 Correct:0.992
 I:180 Error:0.135 Correct:0.995
 I:190 Error:0.132 Correct:0.995
 I:200 Error:0.130 Correct:0.998
 I:210 Error:0.127 Correct:0.998
 I:220 Error:0.125 Correct:0.998
 I:230 Error:0.123 Correct:0.998
 I:240 Error:0.121 Correct:0.998
 I:250 Error:0.120 Correct:0.999
 I:260 Error:0.118 Correct:0.999
 I:270 Error:0.117 Correct:0.999
 I:280 Error:0.115 Correct:0.999
 I:290 Error:0.114 Correct:0.999
 I:300 Error:0.113 Corr

In [76]:
#TEST Data
import sys, numpy as np
from keras.datasets import mnist


np.random.seed(1)


def relu(x):
    return (x >= 0) * x


def relu2deriv(output):
    return output >= 0

(x_train, y_train), (x_test, y_test) = mnist.load_data()
# TRAIN IMAGES
train_images = (x_train[0:1000].reshape(1000, 28 * 28) / 255)
train_labels = np.zeros((len(y_train[0:1000]), 10))

for i, l in enumerate(y_train[0:1000]):
    train_labels[i][l] = 1

# TEST IMAGES
test_images = x_test.reshape(len(x_test), 28 * 28) / 255
test_labels = np.zeros((len(y_test), 10))

for i, l in enumerate(y_test):
    test_labels[i][l] = 1

alpha, iterations, hidden_size = (0.005, 350, 100)
pixels_per_image, num_labels = (784, 10)
weights_0_1 = 0.2 * np.random.random((pixels_per_image, hidden_size)) - 0.1
weights_1_2 = 0.2 * np.random.random((hidden_size, num_labels)) - 0.1

for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    for i in range(len(train_images)):
        layer_0 = train_images[i:i + 1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)
        
        error += np.sum((train_labels[i:i + 1] - layer_2) ** 2)
        correct_cnt += int(np.argmax(layer_2) == \
                           np.argmax(train_labels[i:i + 1]))
        layer_2_delta = (train_labels[i:i + 1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
    if (j % 10 == 0 or j == iterations -1):
        test_error, test_correct_cnt = 0.0, 0

        for i in range(len(test_images)):
            layer_0 = test_images[i:i + 1]
            layer_1 = relu(np.dot(layer_0, weights_0_1))
            layer_2 = np.dot(layer_1, weights_1_2)

            test_error += np.sum((test_labels[i:i + 1] - layer_2) ** 2)
            test_correct_cnt += int(np.argmax(layer_2) == \
                                    np.argmax(test_labels[i:i + 1]))
        
        sys.stdout.write("\ri: " + str(j) + " Test-Err:" + str(test_error/float(len(test_images)))[0:5] +\
        " Test-Acc:" + str(test_correct_cnt/float(len(test_images))))
        print()

i: 0 Test-Err:0.585 Test-Acc:0.6926
i: 10 Test-Err:0.398 Test-Acc:0.8369
i: 20 Test-Err:0.391 Test-Acc:0.837
i: 30 Test-Err:0.401 Test-Acc:0.8289
i: 40 Test-Err:0.412 Test-Acc:0.8186
i: 50 Test-Err:0.423 Test-Acc:0.8106
i: 60 Test-Err:0.434 Test-Acc:0.803
i: 70 Test-Err:0.445 Test-Acc:0.7958
i: 80 Test-Err:0.456 Test-Acc:0.7907
i: 90 Test-Err:0.466 Test-Acc:0.7863
i: 100 Test-Err:0.476 Test-Acc:0.782
i: 110 Test-Err:0.485 Test-Acc:0.7781
i: 120 Test-Err:0.493 Test-Acc:0.7719
i: 130 Test-Err:0.501 Test-Acc:0.7669
i: 140 Test-Err:0.509 Test-Acc:0.763
i: 150 Test-Err:0.517 Test-Acc:0.7588
i: 160 Test-Err:0.524 Test-Acc:0.7562
i: 170 Test-Err:0.531 Test-Acc:0.7522
i: 180 Test-Err:0.538 Test-Acc:0.7482
i: 190 Test-Err:0.544 Test-Acc:0.7432
i: 200 Test-Err:0.550 Test-Acc:0.7407
i: 210 Test-Err:0.556 Test-Acc:0.7359
i: 220 Test-Err:0.561 Test-Acc:0.734
i: 230 Test-Err:0.565 Test-Acc:0.7304
i: 240 Test-Err:0.570 Test-Acc:0.7284
i: 250 Test-Err:0.574 Test-Acc:0.7259
i: 260 Test-Err:0.578 Test-A

In [58]:
#TEST & TRAIN w dropout regularization to prevent overfitting dropout
import sys, numpy as np
from keras.datasets import mnist


np.random.seed(1)


def relu(x):
    return (x >= 0) * x


def relu2deriv(output):
    return output >= 0

(x_train, y_train), (x_test, y_test) = mnist.load_data()
# TRAIN IMAGES
train_images = (x_train[0:1000].reshape(1000, 28 * 28) / 255)
train_labels = np.zeros((len(y_train[0:1000]), 10))

for i, l in enumerate(y_train[0:1000]):
    train_labels[i][l] = 1

# TEST IMAGES
test_images = x_test.reshape(len(x_test), 28 * 28) / 255
test_labels = np.zeros((len(y_test), 10))

for i, l in enumerate(y_test):
    test_labels[i][l] = 1

alpha, iterations, hidden_size = (0.005, 300, 100)
pixels_per_image, num_labels = (784, 10)

weights_0_1 = 0.2 * np.random.random((pixels_per_image, hidden_size)) - 0.1
weights_1_2 = 0.2 * np.random.random((hidden_size, num_labels)) - 0.1

for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    for i in range(len(train_images)):
        layer_0 = train_images[i:i + 1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        dropout_mask = np.random.randint(2, size=layer_1.shape)
        layer_1 *= dropout_mask * 2
        layer_2 = np.dot(layer_1, weights_1_2)
        
        error += np.sum((train_labels[i:i + 1] - layer_2) ** 2)
        correct_cnt += int(np.argmax(layer_2) == \
                           np.argmax(train_labels[i:i + 1]))
        
        layer_2_delta = (train_labels[i:i + 1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
        layer_1_delta *= dropout_mask
        
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
        
    if j % 10 == 0:
        test_error, test_correct_cnt = 0.0, 0

        for i in range(len(test_images)):
            layer_0 = test_images[i:i + 1]
            layer_1 = relu(np.dot(layer_0, weights_0_1))
            layer_2 = np.dot(layer_1, weights_1_2)

            test_error += np.sum((test_labels[i:i + 1] - layer_2) ** 2)
            test_correct_cnt += int(np.argmax(layer_2) == \
                                    np.argmax(test_labels[i:i + 1]))
        sys.stdout.write("\n" + \
                 "I:" + str(j) + \
                 " Test-Err:" + str(test_error / float(len(test_images)))[0:5] + \
                 " Test-Acc:" + str(test_correct_cnt / float(len(test_images))) + \
                 " Train-Err:" + str(error / float(len(train_images)))[0:5] + \
                 " Train-Acc:" + str(correct_cnt / float(len(train_images))))



I:0 Test-Err:0.641 Test-Acc:0.6333 Train-Err:0.891 Train-Acc:0.413
I:10 Test-Err:0.458 Test-Acc:0.787 Train-Err:0.472 Train-Acc:0.764
I:20 Test-Err:0.415 Test-Acc:0.8133 Train-Err:0.430 Train-Acc:0.809
I:30 Test-Err:0.421 Test-Acc:0.8114 Train-Err:0.415 Train-Acc:0.811
I:40 Test-Err:0.419 Test-Acc:0.8112 Train-Err:0.413 Train-Acc:0.827
I:50 Test-Err:0.409 Test-Acc:0.8133 Train-Err:0.392 Train-Acc:0.836
I:60 Test-Err:0.412 Test-Acc:0.8236 Train-Err:0.402 Train-Acc:0.836
I:70 Test-Err:0.412 Test-Acc:0.8033 Train-Err:0.383 Train-Acc:0.857
I:80 Test-Err:0.410 Test-Acc:0.8054 Train-Err:0.386 Train-Acc:0.854
I:90 Test-Err:0.411 Test-Acc:0.8144 Train-Err:0.376 Train-Acc:0.868
I:100 Test-Err:0.411 Test-Acc:0.7903 Train-Err:0.369 Train-Acc:0.864
I:110 Test-Err:0.411 Test-Acc:0.8003 Train-Err:0.371 Train-Acc:0.868
I:120 Test-Err:0.402 Test-Acc:0.8046 Train-Err:0.353 Train-Acc:0.857
I:130 Test-Err:0.408 Test-Acc:0.8091 Train-Err:0.352 Train-Acc:0.867
I:140 Test-Err:0.405 Test-Acc:0.8083 Train-Er

In [27]:
# BATCH GRADIENT DECENT
import numpy as np
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

images, labels = (x_train[0:1000].reshape(1000,28*28) / 255, y_train[0:1000])

one_hot_labels = np.zeros((len(labels),10))
for i,l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test),28*28) / 255
test_labels = np.zeros((len(y_test),10))
for i,l in enumerate(y_test):
    test_labels[i][l] = 1

np.random.seed(1)

def relu(x):
    return (x >= 0) * x # returns x if x > 0

def relu2deriv(output):
    return output >= 0 # returns 1 for input > 0

batch_size = 100
alpha, iterations = (0.001, 300)
pixels_per_image, num_labels, hidden_size = (784, 10, 100)

weights_0_1 = 0.2*np.random.random((pixels_per_image,hidden_size)) - 0.1
weights_1_2 = 0.2*np.random.random((hidden_size,num_labels)) - 0.1

for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    for i in range(int(len(images) / batch_size)):
        batch_start, batch_end = ((i * batch_size),((i+1)*batch_size))

        # grab 128 rows of 784 columns in a batch and process the batch
        layer_0 = images[batch_start:batch_end]
        layer_1 = relu(np.dot(layer_0,weights_0_1))
        dropout_mask = np.random.randint(2,size=layer_1.shape)
        layer_1 *= dropout_mask * 2
        layer_2 = np.dot(layer_1,weights_1_2)

        error += np.sum((labels[batch_start:batch_end] - layer_2) ** 2)
        
        # process each batch
        for k in range(batch_size):
            correct_cnt += int(np.argmax(layer_2[k:k+1]) == np.argmax(labels[batch_start+k:batch_start+k+1]))

            layer_2_delta = (labels[batch_start:batch_end]-layer_2)/batch_size
            layer_1_delta = layer_2_delta.dot(weights_1_2.T)* relu2deriv(layer_1)
            layer_1_delta *= dropout_mask

            weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
            weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
            
    if(j%10 == 0):
        test_error = 0.0
        test_correct_cnt = 0

        for i in range(len(test_images)):
            layer_0 = test_images[i:i+1]
            layer_1 = relu(np.dot(layer_0,weights_0_1))
            layer_2 = np.dot(layer_1, weights_1_2)

            test_error += np.sum((test_labels[i:i+1] - layer_2) ** 2)
            test_correct_cnt += int(np.argmax(layer_2) == np.argmax(test_labels[i:i+1]))

        sys.stdout.write("\n" + \
                         "I:" + str(j) + \
                         " Test-Err:" + str(test_error/ float(len(test_images)))[0:5] +\
                         " Test-Acc:" + str(test_correct_cnt/ float(len(test_images)))+\
                         " Train-Err:" + str(error/ float(len(images)))[0:5] +\
                         " Train-Acc:" + str(correct_cnt/ float(len(images))))


I:0 Test-Err:0.815 Test-Acc:0.3832 Train-Err:1.284 Train-Acc:0.165
I:10 Test-Err:0.568 Test-Acc:0.7173 Train-Err:0.591 Train-Acc:0.672
I:20 Test-Err:0.510 Test-Acc:0.7571 Train-Err:0.532 Train-Acc:0.729
I:30 Test-Err:0.485 Test-Acc:0.7793 Train-Err:0.498 Train-Acc:0.754
I:40 Test-Err:0.468 Test-Acc:0.7877 Train-Err:0.489 Train-Acc:0.749
I:50 Test-Err:0.458 Test-Acc:0.793 Train-Err:0.468 Train-Acc:0.775
I:60 Test-Err:0.452 Test-Acc:0.7995 Train-Err:0.452 Train-Acc:0.799
I:70 Test-Err:0.446 Test-Acc:0.803 Train-Err:0.453 Train-Acc:0.792
I:80 Test-Err:0.451 Test-Acc:0.7968 Train-Err:0.457 Train-Acc:0.786
I:90 Test-Err:0.447 Test-Acc:0.795 Train-Err:0.454 Train-Acc:0.799
I:100 Test-Err:0.448 Test-Acc:0.793 Train-Err:0.447 Train-Acc:0.796
I:110 Test-Err:0.441 Test-Acc:0.7943 Train-Err:0.426 Train-Acc:0.816
I:120 Test-Err:0.442 Test-Acc:0.7966 Train-Err:0.431 Train-Acc:0.813
I:130 Test-Err:0.441 Test-Acc:0.7906 Train-Err:0.434 Train-Acc:0.816
I:140 Test-Err:0.447 Test-Acc:0.7874 Train-Err:0

In [40]:
# IMPROVED ACTIVATION FUNCTIONS
import numpy as np, sys
np.random.seed(1)

from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

images, labels = (x_train[0:1000].reshape(1000,28*28) / 255, y_train[0:1000])

one_hot_labels = np.zeros((len(labels),10))
for i,l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test),28*28) / 255
test_labels = np.zeros((len(y_test),10))
for i,l in enumerate(y_test):
    test_labels[i][l] = 1

def tanh(x):
    return np.tanh(x)

def tanh2deriv(output):
    return 1 - (output ** 2)

def softmax(x):
    temp = np.exp(x)
    return temp / np.sum(temp, axis=1, keepdims=True)

alpha, iterations, hidden_size = (2, 300, 100)
pixels_per_image, num_labels = (784, 10)
batch_size = 100

weights_0_1 = 0.02*np.random.random((pixels_per_image,hidden_size))-0.01
weights_1_2 = 0.2*np.random.random((hidden_size,num_labels)) - 0.1

for j in range(iterations):
    correct_cnt = 0
    
    for i in range(int(len(images) / batch_size)):
        batch_start, batch_end = ((i * batch_size),((i+1)*batch_size))

        layer_0 = images[batch_start:batch_end]
        # change act function
        layer_1 = tanh(np.dot(layer_0,weights_0_1))
        dropout_mask = np.random.randint(2,size=layer_1.shape)
        layer_1 *= dropout_mask * 2
        # change act function
        layer_2 = softmax(np.dot(layer_1,weights_1_2))

        #error += np.sum((labels[batch_start:batch_end] - layer_2) ** 2)
        for k in range(batch_size):
            correct_cnt += int(np.argmax(layer_2[k:k+1]) == np.argmax(labels[batch_start+k:batch_start+k+1]))

        layer_2_delta = (labels[batch_start:batch_end]-layer_2)/ (batch_size * layer_2.shape[0])

        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * tanhderiv(layer_1)
        layer_1_delta *= dropout_mask

        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
           
        test_correct_cnt = 0
        
        for i in range(len(test_images)):
            layer_0 = test_images[i:i+1]
            layer_1 = tanh(np.dot(layer_0,weights_0_1))
            layer_2 = np.dot(layer_1, weights_1_2)

            #test_error += np.sum((test_labels[i:i+1] - layer_2) ** 2)
            test_correct_cnt += int(np.argmax(layer_2) == np.argmax(test_labels[i:i+1]))
            
    if(j % 10 == 0):
        #test_error = 0.0     
        sys.stdout.write("\n" + \
                         "I:" + str(j) + \
                         " Test-Acc:" + str(test_correct_cnt/ float(len(test_images)))+\
                         " Train-Acc:" + str(correct_cnt/ float(len(images))))


I:0 Test-Acc:0.394 Train-Acc:0.156
I:10 Test-Acc:0.6867 Train-Acc:0.723
I:20 Test-Acc:0.7025 Train-Acc:0.732
I:30 Test-Acc:0.734 Train-Acc:0.763
I:40 Test-Acc:0.7663 Train-Acc:0.794
I:50 Test-Acc:0.7913 Train-Acc:0.819
I:60 Test-Acc:0.8102 Train-Acc:0.849
I:70 Test-Acc:0.8228 Train-Acc:0.864
I:80 Test-Acc:0.831 Train-Acc:0.867
I:90 Test-Acc:0.8364 Train-Acc:0.885
I:100 Test-Acc:0.8407 Train-Acc:0.883
I:110 Test-Acc:0.845 Train-Acc:0.891
I:120 Test-Acc:0.8481 Train-Acc:0.901
I:130 Test-Acc:0.8505 Train-Acc:0.901
I:140 Test-Acc:0.8526 Train-Acc:0.905
I:150 Test-Acc:0.8555 Train-Acc:0.914
I:160 Test-Acc:0.8577 Train-Acc:0.925
I:170 Test-Acc:0.8596 Train-Acc:0.918
I:180 Test-Acc:0.8619 Train-Acc:0.933
I:190 Test-Acc:0.863 Train-Acc:0.933
I:200 Test-Acc:0.8642 Train-Acc:0.926
I:210 Test-Acc:0.8653 Train-Acc:0.931
I:220 Test-Acc:0.8668 Train-Acc:0.93
I:230 Test-Acc:0.8672 Train-Acc:0.937
I:240 Test-Acc:0.8681 Train-Acc:0.938
I:250 Test-Acc:0.8687 Train-Acc:0.937
I:260 Test-Acc:0.8684 Train-

In [2]:
# CONVOLUTIONAL NETWORKS
import numpy as np
import sys

from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

images, labels = (x_train[0:1000].reshape(1000, 28 * 28) / 255,
                  y_train[0:1000])

one_hot_labels = np.zeros((len(labels), 10))
for i, l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test), 28 * 28) / 255
test_labels = np.zeros((len(y_test), 10))
for i, l in enumerate(y_test):
    test_labels[i][l] = 1

np.random.seed(1)

def tanh(x):
    return np.tanh(x)


def tanh2deriv(output):
    return 1 - (output ** 2)


def softmax(x):
    temp = np.exp(x)
    return temp / np.sum(temp, axis=1, keepdims=True)


alpha, iterations = (2, 300)
pixels_per_image, num_labels = (784, 10)
batch_size = 128

input_rows = 28
input_cols = 28

kernel_rows = 3
kernel_cols = 3
num_kernels = 16

hidden_size = ((input_rows - kernel_rows) * (input_cols - kernel_cols)) * num_kernels

kernels = 0.02 * np.random.random((kernel_rows * kernel_cols, num_kernels)) - 0.01
# weights_0_1 = 0.02*np.random.random((pixels_per_image,hidden_size))-0.01
weights_1_2 = 0.2 * np.random.random((hidden_size, num_labels)) - 0.1

#print(kernels.shape)
#print(weights_1_2.shape)


def get_image_section(layer, row_from, row_to, col_from, col_to):
    section = layer[:, row_from:row_to, col_from:col_to]
    return section.reshape(-1, 1, row_to - row_from, col_to - col_from)


for j in range(iterations):
    correct_cnt = 0
    for i in range(int(len(images) / batch_size)):
        batch_start, batch_end = ((i * batch_size), ((i + 1) * batch_size))

        # grab 128 rows of 784 columns in a batch
        layer_0 = images[batch_start:batch_end]

        # reshape the long string of 784 pixels back into a 28 * 28 matrix
        # batch still has 128 rows of 28*28 matrix
        layer_0 = layer_0.reshape(layer_0.shape[0], 28, 28)
        layer_0.shape

        # create list
        sects = list()
        # convolve the input layer and slice up in batches, add sections to list
        for row_start in range(layer_0.shape[1] - kernel_rows):
            for col_start in range(layer_0.shape[2] - kernel_cols):
                sect = get_image_section(layer_0,
                                         row_start,
                                         row_start + kernel_rows,
                                         col_start,
                                         col_start + kernel_cols)
                sects.append(sect)
        # house keeping on sections
        expanded_input = np.concatenate(sects, axis=1)
        es = expanded_input.shape
        flattened_input = expanded_input.reshape(es[0] * es[1], -1)
        # get the dot product between the kernel and the sections
        kernel_output = flattened_input.dot(kernels)
        # use the activation function but need to reshape, use -1 to let python figure it out
        layer_1 = tanh(kernel_output.reshape(es[0], -1))
        dropout_mask = np.random.randint(2, size=layer_1.shape)
        layer_1 *= dropout_mask * 2
        layer_2 = softmax(np.dot(layer_1, weights_1_2))

        for k in range(batch_size):
            labelset = labels[batch_start + k:batch_start + k + 1]
            _inc = int(np.argmax(layer_2[k:k + 1]) ==
                       np.argmax(labelset))
            correct_cnt += _inc

        layer_2_delta = (labels[batch_start:batch_end] - layer_2) \
                        / (batch_size * layer_2.shape[0])
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * \
                        tanh2deriv(layer_1)
        layer_1_delta *= dropout_mask
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        l1d_reshape = layer_1_delta.reshape(kernel_output.shape)
        k_update = flattened_input.T.dot(l1d_reshape)
        kernels -= alpha * k_update

    test_correct_cnt = 0

    for i in range(len(test_images)):

        layer_0 = test_images[i:i + 1]
        # layer_1 = tanh(np.dot(layer_0,weights_0_1))
        layer_0 = layer_0.reshape(layer_0.shape[0], 28, 28)
        layer_0.shape

        sects = list()
        for row_start in range(layer_0.shape[1] - kernel_rows):
            for col_start in range(layer_0.shape[2] - kernel_cols):
                sect = get_image_section(layer_0,
                                         row_start,
                                         row_start + kernel_rows,
                                         col_start,
                                         col_start + kernel_cols)
                sects.append(sect)

        expanded_input = np.concatenate(sects, axis=1)
        es = expanded_input.shape
        flattened_input = expanded_input.reshape(es[0] * es[1], -1)

        kernel_output = flattened_input.dot(kernels)
        layer_1 = tanh(kernel_output.reshape(es[0], -1))
        layer_2 = np.dot(layer_1, weights_1_2)

        test_correct_cnt += int(np.argmax(layer_2) ==
                                np.argmax(test_labels[i:i + 1]))
    if (j % 10 == 0):
        sys.stdout.write("\n" + \
                         "I:" + str(j) + \
                         " Test-Acc:" + str(test_correct_cnt / float(len(test_images))) + \
                         " Train-Acc:" + str(correct_cnt / float(len(images))))


Using TensorFlow backend.



I:0 Test-Acc:0.0288 Train-Acc:0.055
I:10 Test-Acc:0.3563 Train-Acc:0.181
I:20 Test-Acc:0.0133 Train-Acc:0.022
I:30 Test-Acc:0.6608 Train-Acc:0.426
I:40 Test-Acc:0.7352 Train-Acc:0.54
I:50 Test-Acc:0.4202 Train-Acc:0.21
I:60 Test-Acc:0.7401 Train-Acc:0.525
I:70 Test-Acc:0.7973 Train-Acc:0.64
I:80 Test-Acc:0.8237 Train-Acc:0.666
I:90 Test-Acc:0.8393 Train-Acc:0.687
I:100 Test-Acc:0.8511 Train-Acc:0.737
I:110 Test-Acc:0.8588 Train-Acc:0.754
I:120 Test-Acc:0.8629 Train-Acc:0.753
I:130 Test-Acc:0.8694 Train-Acc:0.753
I:140 Test-Acc:0.8666 Train-Acc:0.756
I:150 Test-Acc:0.873 Train-Acc:0.785
I:160 Test-Acc:0.8751 Train-Acc:0.774
I:170 Test-Acc:0.8764 Train-Acc:0.79
I:180 Test-Acc:0.8778 Train-Acc:0.794
I:190 Test-Acc:0.8774 Train-Acc:0.787
I:200 Test-Acc:0.8776 Train-Acc:0.792
I:210 Test-Acc:0.8788 Train-Acc:0.804
I:220 Test-Acc:0.8793 Train-Acc:0.799
I:230 Test-Acc:0.8807 Train-Acc:0.8
I:240 Test-Acc:0.8787 Train-Acc:0.809
I:250 Test-Acc:0.8786 Train-Acc:0.808
I:260 Test-Acc:0.8799 Train-A